name: art_connoisseur_quiz
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  stream_transform: ^2.1.0
  auto_route: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0


flutter:

  uses-material-design: true
